version: "3"
services:
  web: &web
    container_name: web
    build: .
    env_file: ../.env.development
    restart: always
    stdin_open: true
    tty: true
    working_dir: "/app"
    ports:
      - 8080:8080
    volumes:
      - ../:/app
      - v_node_modules:/app/node_modules
volumes:
  v_node_modules:
